name: Build and Zip Chrome Extension

on:
  workflow_dispatch:

jobs:
  build:
    name: Build
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: "yarn"

      - name: Install dependencies
        run: yarn

      - name: Build Chrome
        run: yarn build:chrome

      - name: Upload Chrome extension artifacts
        uses: actions/upload-artifact@v4
        with:
          name: koodo-reader-extension-chrome
          path: dist_chrome

      - name: Extract version from package.json
        id: version
        run: echo "version=v$(node -p \"require('./package.json').version\")" >> $GITHUB_OUTPUT

      - name: Zip build output for release
        run: |
          cd dist_chrome && zip -r "../koodo-reader-extension-chrome-${{ steps.version.outputs.version }}.zip" .

      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.version.outputs.version }}
          name: ${{ steps.version.outputs.version }}
          artifacts: koodo-reader-extension-chrome-${{ steps.version.outputs.version }}.zip
          artifactContentType: application/zip
          skipIfReleaseExists: true
          generateReleaseNotes: true
